### ISSUE TITLE
I want r6502 gem.

### ISSUE THREAD

**Issue by haramako** [joelanders/r6502#4]
Hi, Thanks you this project.

I'm using r6502 in my 6502 compiler project to test.
Could you make r6502 a GEM?

Or I embed r6502 in my project?
In this case, I hope you license by open source friendly license.

My compiler is now under construction.
https://github.com/haramako/fc

**Comment by joelanders** [comment]
Added MIT License!
And I'll look later today at turning this into a gem.

Thanks for the interest!

**Comment by joelanders** [comment]
Ok, it's now a gem and on RubyGems.

**Comment by haramako** [comment]
Thanks a lot :)
